import {
   faArrowDown, faArrowUp,
   faBars,
   faBuilding, faCheck, faCheckCircle, faClock, faCommentAlt, faCommentSlash,
   faCopy, faEraser, faExclamation, faFileAlt, faFileDownload, faFileExcel, faFilePdf, faFileUpload, faFileWord,
   faGift, faHistory,
   faHome, faLaptopHouse, faMinus, faPenAlt, faPlus, faSearch,
   faSignOutAlt, faSpinner, faTasks, faTimes, faUmbrellaBeach, faUserEdit, faUsers,
   faUserSecret
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeIcons = [
   faBars,
   faBuilding,
   faCopy,
   faGift,
   faUserSecret,
   faSignOutAlt,
   faHome,
   faHistory,
   faLaptopHouse,
   faCommentAlt,
   faCommentSlash,
   faTasks,
   faUsers,
   faTimes,
   faCheck,
   faCheckCircle,
   faClock,
   faPenAlt,
   faFileAlt,
   faFilePdf,
   faFileWord,
   faFileExcel,
   faFileDownload,
   faExclamation,
   faFileUpload,
   faEraser,
   faArrowDown,
   faArrowUp,
   faPlus,
   faMinus,
   faSpinner,
   faSearch,
   faUserEdit,
   faUmbrellaBeach
];
