export const primeVueLocaleOptions = {
   startsWith: 'Starts with',
   contains: 'Contains',
   notContains: 'Not contains',
   endWith: 'Ends with',
   equals: 'Equals',
   notEquals: 'Not equals',
   noFilter: 'No Filter',
   lt: 'Less than',
   lte: 'Less than or equal to',
   gt: 'Greater than',
   gte: 'Greater than or equal to',
   dateIs: 'Date is',
   dateIsNot: 'Date is not',
   dateBefore: 'Date is before',
   dateAfter: 'Date is after',
   clear: 'Clear',
   apply: 'Apply',
   matchAll: 'Match All',
   matchAny: 'Match Any',
   addRule: 'Add Rule',
   removeRule: 'Remove Rule',
   accept: 'Да',
   reject: 'Нет',
   choose: 'Выбрать',
   upload: 'Загрузить',
   cancel: 'Отмена',
   dayNames: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
   dayNamesShort: ['Вскр', 'Пон', 'Втр', 'Ср', 'Чтв', 'Пт', 'Сбт'],
   dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
   monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
   monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
   today: 'Today',
   weekHeader: 'Wk',
   firstDayOfWeek: 1,
   dateFormat: 'dd.mm.yy',
   weak: 'Weak',
   medium: 'Medium',
   strong: 'Strong',
   passwordPrompt: 'Введите пароль',
   emptyFilterMessage: 'Результаты не найдены',
   emptyMessage: 'Отсутствуют опции для выбора'
};
